# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_review_app', '0003_auto_20170831_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='poked_another',
        ),
        migrations.RemoveField(
            model_name='user',
            name='were_poked',
        ),
    ]
