# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-30 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('user_name', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('password', models.CharField(default='', max_length=255)),
                ('date_hired', models.CharField(default='', max_length=255)),
                ('were_poked', models.IntegerField(default=0)),
                ('poked_another', models.IntegerField(default=0)),
            ],
        ),
    ]
