# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_review_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_poked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poked', to='belt_review_app.User')),
                ('user_poker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker', to='belt_review_app.User')),
            ],
        ),
    ]
