# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_review_app', '0002_poke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='poked_another',
        ),
        migrations.RemoveField(
            model_name='user',
            name='were_poked',
        ),
        migrations.AddField(
            model_name='user',
            name='poke_history',
            field=models.IntegerField(default=0),
        ),
    ]
